name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: restore
        run: msbuild -t:restore
      - name: pack
        run: msbuild -t:pack
      - name: publish
        run: dotnet nuget push "HAF.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: build documentation
        working-directory: Documentation
        run: docfx docfx.json
        continue-on-error: false
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: hosting162236.af9aa.netcup.net
          username: haf-documentation
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: Documentation/Site

          
