name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: restore
        run: msbuild -t:restore
      - name: pack
        run: msbuild -t:pack
      - name: read project file
        id: project-file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./HAF.csproj
      - name: extract version from project file
        uses: actions-ecosystem/action-regex-match@v2
        id: version-match
        with:
          text: ${{ steps.project-file.outputs.content }}
          regex: '<Version>(.*)</Version>'
      - name: update version in documentation
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: ./Documentation/docfx.json
          _output-file: ./Documentation/docfx.json
          X.X.X: ${{ steps.version-match.outputs.group1 }}
      - name: update version in documentation
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: ./Documentation/index.md
          _output-file: ./Documentation/index.md
          X.X.X: ${{ steps.version-match.outputs.group1 }}
      - name: publish
        run: dotnet nuget push "HAF.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
  docs:
    name: update documentation
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: build documentation
        working-directory: Documentation
        run: docfx docfx.json
        continue-on-error: false
      - name: publish documentation
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: hosting162236.af9aa.netcup.net
          username: haf-documentation
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: Documentation/Site/

          
