name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: HAF.csproj
          PACKAGE_NAME: HAF
          VERSION_FILE_PATH: Properties/AssemblyInfo.cs
          VERSION_REGEX: AssemblyVersion\("(.*)"\)
          TAG_COMMIT: true
          TAG_FORMAT: master/*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
